name: Build Debian Package
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y devscripts debhelper python3-venv git

    - name: Build Debian package
      run: |
        dpkg-buildpackage -b -uc

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: debian-package
        path: '../*.deb'

